spring:
  datasource:
#    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
    url: jdbc:mysql://localhost:3306/quiz
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: beans,conditions,configprops,env,health,info,mappings,metrics

server:
  servlet:
    context-path: /quiz-app
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-message: always